### ISSUE TITLE
FR_regularizer的疑惑

### ISSUE THREAD

**Issue by ha2ha2** [zwx8981/PerceptualAttack_BIQA#1]
你好， 请问关于这个待优化的目标函数中的后一项config.lamda * FR_reg，是要最大化这一项来保证对抗样本和原图看起来尽可能像，这么理解对吗？我在网上查阅之后发现SSIM越大越相似，LPIPS, DISTS, Linf越小越相似，所以没能理解Fr_reg这里对于DISTS和Linf的处理。
![image](https://user-images.githubusercontent.com/40172082/220229636-aee31d99-0888-41df-bdda-879bc54f3948.png)

**Comment by zwx8981** [comment]
@ha2ha2 你好，你理解的没问题，这里是最大化FR_reg来保证对抗样本跟原图的相似性，因为SSIM和DISTS都是越大越好，LPIPS和Linf是越小越好，这部分应该是整理代码时弄错了，非常不好意思，目前已修正，你再看看，如果还有问题我们再讨论。

**Comment by ha2ha2** [comment]
> @ha2ha2 你好，你理解的没问题，这里是最大化FR_reg来保证对抗样本跟原图的相似性，因为SSIM和DISTS都是越大越好，LPIPS和Linf是越小越好，这部分应该是整理代码时弄错了，非常不好意思，目前已修正，你再看看，如果还有问题我们再讨论。

非常感谢您的解答！关于DISTS，我用这个代码里的DISTS_mode去测试，发现原图和原图的结果是0，原图和对抗样本的结果是0.00几，原图和随机噪声的结果是0.8 ，好像DISTS这个是越小越相似
![ZID3I888(XNN_S`({O%8ORJ](https://user-images.githubusercontent.com/40172082/220242400-206f75dc-98c7-4eb2-8b93-f452b29b72cc.png)
![JLFN{9TTENGC$XX%B606X Y](https://user-images.githubusercontent.com/40172082/220242433-6f45f518-d22d-4e71-ba67-52100f52b6e4.png)
![L2$SED}69F}RY(Z2XH%2JJD](https://user-images.githubusercontent.com/40172082/220242554-9b574948-553c-45e8-8154-d1c2cef30e70.png)

**Comment by zwx8981** [comment]
@ha2ha2 感谢反馈，那应该就是DISTS内部做了符号取反，可以检查一下

**Comment by ha2ha2** [comment]
感谢您的解答！
